#!/bin/bash
USER_AGENT="JackBot"
HUBOT_SLACK_TOKEN="TOKEN_FROM_SLACK"
BASE_URL="https://api.example.org"
ACCESS_TOKEN="Bearer somethingTheServiceWillAccept"

export USER_AGENT
export BASE_URL
export ACCESS_TOKEN
export HUBOT_SLACK_TOKEN

./bin/hubot --adapter slack

